### ISSUE TITLE
Add placeholder text when there are no dreams created yet

### ISSUE THREAD

**Issue by ArtyomArtamonov** [ArtyomArtamonov/SleepWriter#15]
It should be simple text to hide empty space at second tab, when there are no dreams created yet

**Comment by samgusa** [comment]
Hello, May I give this a try please? Thank you

**Comment by ArtyomArtamonov** [comment]
> Hello, May I give this a try please? Thank you

Feel free to send pull request.

**Comment by samgusa** [comment]
I submitted the pull request.
